# Generated by Django 4.1.5 on 2023-01-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
